language: node_js

node_js:
  - "node"

cache: npm

os:
  - osx

install:
- npm install gitbook-cli
- gitbook install
- gitbook build

script:
- echo "skipping test"

deploy:
  provider: s3
  access_key_id: "AKIAJLEF6XRKWDYLCF2Q"
  secret_access_key: secure
  bucket: "gitbook-testing"
  local_dir: _book
  upload-dir: test-source-book
  acl: public_read
  skip_cleanup: true

branches:
  only:
  - master

env:
  global:
    secure: HO8Vcu2yQB75Ga/U0svOiSFHOcVRD7FSVh1E6GzZ6q6l1YCZNo4hy537A8k5ts+8XXiUfo8X3efottjtRlrFES5AvVKsJ5sLmTsYzZR3qIsPTczWr7IpVvIBtEjM5zSY3Qz8Tp36T4odCOxUjbbs+aAUWlzQQJnPC0ptFhaMx/o1E2D/98mWqD14YiPc29pG+OMfXhLhkbv6Lq9yv24fOURP93mAJC7Eq/dt6UoXW3ap+zKF9AEK3esV5Smaop9MgNmAbFCUGlwtiaTBMk78LJIg4RIabO3O+6Ljk51XqHLY7J7f2RnnNmKjdF9dCnFWz/BtlkMcdigBafturIo0ZHEF6Hkm4mFXEATYQcyiNVw+lEiqlkMvfW6VUhONMbn5t2Y8xk1R8BDf4oGpP6DsIHpZQoznWBNHi0IzLj2TK7GiTBHtQ7nLd9dEeNrPCsir8VOKz5DgITqVhpwAoXlj4hdf0ErjjyXGjMblu/cFRF7SgotWY/zv5zWpQnnivBG2d4Y0G+YsA+UXg2c9aRlf7i/zltIRXmoVraiscykyDt9TU7BrdsxvdnQDVf/MYB4HiL4oejaySfA5uhfXhBQFDVaAehR6Ws57Q9rDG5wkTdPpIiGQ9lB9VLixRgNLeL95voTdStQ5V3ZxBLzH/vAZVq7O3MI4LeiNqMLKL/8+v40=
